name: Build And Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
        with:
          # Check out the latest commit on the branch, rather than the (default) merge commit)
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run Tests
        uses: ./.github/actions/run_tests