name: Build And Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        uses: ./.github/actions/run_tests