name: Set test status

on:
  workflow_call:
  workflow_dispatch:

jobs:
  set-test-status:
    name: Set Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run the action
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'Bump Build / Run Tests'
        description: 'Passed'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha || github.sha }}